### ISSUE TITLE
Problem with parentheses

### ISSUE THREAD

**Issue by nolleto** [brunoskonrad/jquery-linkalize#6]
There is a problem when the url is between parentheses. The plugin consider the lasr parentheses `)` as part of url. For example:

Before plugin:
`<p>I like google (www.google.com).</p>`
I like google (www.google.com).

After plugin:
`<p>I like google (<a href="www.google.com)">www.google.com)</a>.</p>`
I like google ([www.google.com)](www.google.com).

Be careful with url that has parentheses, like:
https://msdn.microsoft.com/pt-br/library/system.string.format(v=vs.110).aspx

**Comment by brunoskonrad** [comment]
Thanks for the feedback. I'll check that as soon as possible, @nolleto.

**Comment by nolleto** [comment]
Bro, try use this Regex: 

```
/(?:(?:https?|ftp|file):\/\/|www\.|ftp\.)(?:\([-A-Z0-9+&@#\/%=~_|$?!:,.]*\)|[-A-Z0-9+&@#\/%=~_|$?!:,.])*(?:\([-A-Z0-9+&@#\/%=~_|$?!:,.]*\)|[A-Z0-9+&@#\/%=~_|$])/igm
```

**Comment by brunoskonrad** [comment]
@nolleto see the PR #7. It should fix this issue. :)

**Comment by brunoskonrad** [comment]
![yeah](https://cloud.githubusercontent.com/assets/632453/11210834/0cad5d80-8d12-11e5-84f2-412db2bdf704.gif)
